#!/bin/bash

API="https://raw.githubusercontent.com/00life/bash/refs/heads/master/raspberrypi_remote";
URL_PI="http://192.168.2.24:8112/json"
CODE=$(mktemp); curl -sL $API -o ${CODE};
PATH_LOG=${HOME}/github.log;

#/ [ Deluge torrent commands ]
#/ ---------------------------
#/ curl -d '{"method": "auth.login", "params": ["your_password"], "id": 1}' -K curl.cfg
#/ curl -b cookie_deluge.txt -d '{"method": "core.add_torrent_magnet", "params": ["<magnet_uri_here>", {}], "id": 1}' http://localhost:8112/json
#/ curl -b cookie_deluge.txt -d '{"method": "web.connected", "params": [], "id": 1}' http://localhost:8112/json
#/ curl -b cookie_deluge.txt -d '{"method": "web.add_torrents", "params": [[{"path":"/path/to/your/torrent/file.torrent", "options":null}]], "id": 1}' http://localhost:8112/json
#/ curl -b cookie_deluge.txt -d '{"method": "web.get_torrent_files", "params": ["<torrent_id_here>"], "id": 1}' http://localhost:8112/json
#/ curl -d '{"method": "core.add_torrent_magnet", "params": ["magnet:?xt=urn:btih:...", {}], "id": 1}' -K curl.cfg

export CURL_COOKIE=$(mktemp --suffix=".txt");
curl -c $CURL_COOKIE --compressed -H "Content-Type: application/json" -d '{"method": "auth.login", "params": ["pi"], "id": 1}' ${URL_PI};

MAGNET='magnet:?xt=urn:btih:6d90f05977199f65a8838e4291cfa52dbb581d5f&dn=%5BSubsPlease%5D%20Release%20that%20Witch%20-%2004%20%28720p%29%20%5B5ACCE2F1%5D.mkv&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce'

echo "-------------";
echo test10;
echo "---------------";
cat $CURL_COOKIE
echo "------------------";
COMMAND="curl -c \"$CURL_COOKIE\" --compressed -H \"Content-Type: application/json\" -H \"Accept: application/json\" -d '{\"method\": \"core.add_torrent_magnet\", \"params\": [\""$MAGNET"\", {}], \"id\": 1}' $URL_PI ";

echo $COMMAND;

eval $COMMAND;
#func_compare() {

#  if [[ ! -f $PATH_LOG ]]; then
#    # echo "File does not exit. Creating github.log.  Exit 1";
#    echo "" > $PATH_LOG;
#    exit 1

#  elif cmp -s "$CODE" "$PATH_LOG"; then
#    # echo "Files are identical. Exit 1";
#    exit 1

#  else
#    # echo "Files are different.  Exit 0";
#    cat $CODE > $PATH_LOG;
#    eval "$COMMAND";
#    sudo rm -rf /tmp/*;
#	exit 0
#  fi
#};

#func_compare;
